=== Garchypielago/LLMM/LLMM_VCS/XML/Profe/XSD/Ejercicio10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="jornada">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="equipos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo" type="equipoType">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="partidosJornada">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="partido" type="partidoType" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="equipoType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="entrenador" type="xs:string" />
            <xs:element name="localidad" type="xs:string" />
            <xs:element name="posicion" type="xs:nonNegativeInteger" />
            <xs:element name="partidos" type="computoPartidosType" />
            <xs:element name="golaveraje" type="golaverajeType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="computoPartidosType">
        <xs:sequence>
            <xs:element name="jugados" type="xs:nonNegativeInteger" />
            <xs:element name="perdidos" type="xs:nonNegativeInteger" />
            <xs:element name="empatados" type="xs:nonNegativeInteger" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="golaverajeType">
        <xs:sequence>
            <xs:element name="favor" type="xs:nonNegativeInteger" />
            <xs:element name="contra" type="xs:nonNegativeInteger" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="partidoType">
        <xs:sequence>
            <xs:element name="local" type="xs:string" />
            <xs:element name="visitante" type="xs:string" />
            <xs:element name="golesLocal" type="xs:nonNegativeInteger" default="0" />
            <xs:element name="golesVisitante" type="xs:nonNegativeInteger" default="0" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Garchypielago/LLMM/LLMM_VCS/XML/Profe/XSD/Ejercicio10.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<jornada xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejercicio10.xsd">
    <equipos>
        <equipo>
            <nombre></nombre>
            <entrenador></entrenador>
            <localidad></localidad>
            <posicion>3</posicion>
            <partidos>
                <jugados>4</jugados>
                <perdidos>5</perdidos>
                <empatados>1</empatados>
            </partidos>
            <golaveraje>
                <favor>0</favor>
                <contra>1</contra>
            </golaveraje>
        </equipo>
    </equipos>
    <partidosJornada>
        <partido>
            <local></local>
            <visitante></visitante>
            <golesLocal></golesLocal>
            <golesVisitante></golesVisitante>
        </partido>
    </partidosJornada>
</jornada>
