=== Garchypielago/LLMM/LLMM_VCS/XML/Profe/XSD/Ejercicio25.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="temporada">
        <xs:complexType>
            <xs:sequence>
                <!-- Pongo un minoccurs 0 porque antes de empezar la liga no hay jornadas -->
                <xs:element name="jornada" minOccurs="0" maxOccurs="5">
                    <xs:complexType>
                        <xs:sequence minOccurs="0">
                            <!-- Pongo un minoccurs y maxoccurs 3 porque nos dicen que siempre hay 3 partidos -->
                            <xs:element name="partido" type="tipoPartido" minOccurs="3" maxOccurs="3"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="numero" use="required">
                            <!-- Este tipo se podría haber definido de forma independiente. Lo dejo así para ver las dos cosas.-->
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"></xs:minInclusive>
                                    <xs:maxInclusive value="5"></xs:maxInclusive>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="anio" type="xs:integer" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tipoPartido">
        <xs:sequence>
            <xs:element name="fecha" type="xs:date" />
            <xs:element name="estadio" type="tipoEstadio"></xs:element>
            <xs:element name="local" type="xs:string" />
            <xs:element name="visitante" type="xs:string" />
            <xs:choice>
                <xs:element name="resultado" type="tipoResultado"></xs:element>
                <xs:element name="aplazado" type="tipoVacio" />
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="numero" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"></xs:minInclusive>
                    <xs:maxInclusive value="3"></xs:maxInclusive>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- Tipo de dato para los espectadores. Esto de extension no lo hemos visto en clase... -->
    <xs:complexType name="tipoEstadio">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="espectadores" type="tipoEspectadores" default="0" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="tipoEspectadores">
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="80000"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tipoResultado">
        <xs:attribute name="local" type="xs:nonNegativeInteger" use="required" />
        <xs:attribute name="vistante" type="xs:nonNegativeInteger" use="required" />
    </xs:complexType>

    <xs:complexType name="tipoVacio">
        <xs:sequence></xs:sequence>
    </xs:complexType>

</xs:schema>

=== Garchypielago/LLMM/LLMM_VCS/XML/Profe/XSD/Ejercicio25.xml
<?xml version="1.0" encoding="UTF-8"?>
<temporada xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejercicio25.xsd" anio="2000">
    <jornada numero="1">
        <partido numero="1">
            <fecha>2002-02-02</fecha>
            <estadio espectadores="80000">La condomina</estadio>
            <local>RC Murcia</local>
            <visitante>Real Sociedad</visitante>
            <resultado local="3" vistante="2" />
        </partido>
        <partido numero="2">
            <fecha>2002-02-03</fecha>
            <estadio>Santiago Bernabeu</estadio>
            <local>Real Madrid</local>
            <visitante>Villareal</visitante>
            <aplazado />
        </partido>
        <partido numero="3">
            <fecha>2002-02-03</fecha>
            <estadio>Santiago Bernabeu</estadio>
            <local>Real Madrid</local>
            <visitante>Villareal</visitante>
            <aplazado />
        </partido>
    </jornada>
    <jornada numero="2">
        <!-- AquÃ­ datos de la Jornada 2 -->
    </jornada>
</temporada>
