<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE facturacion [
    <!ELEMENT facturacion (comercio, periodo, tickets)>
    <!--Comercio -->
    <!ELEMENT comercio (nombreComercio, direccionComercio, tlfComercio)>
    <!ELEMENT nombreComercio (#PCDATA)>
    <!ELEMENT direccionComercio (#PCDATA)>
    <!ELEMENT tlfComercio (#PCDATA)>
    <!ATTLIST comercio cif CDATA #REQUIRED>
    <!-- Periodo -->
    <!ELEMENT periodo (inicioPeriodo, finPeriodo)>
    <!ELEMENT inicioPeriodo (#PCDATA)>
    <!ELEMENT finPeriodo (#PCDATA)>
    <!-- tickets -->
    <!ELEMENT tickets (ticket*)>
    <!ELEMENT ticket (importeSinIva, importeIva, importe, formaPago, articulos)>
    <!ELEMENT importeSinIva (#PCDATA)>
    <!ELEMENT importeIva (#PCDATA)>
    <!ELEMENT importe (#PCDATA)>
    <!ELEMENT formaPago (efectivo|tarjeta)>
    <!ELEMENT efectivo (EMPTY)>
    <!ELEMENT tarjeta (numeracion, titular)>
    <!ELEMENT numeracion (#PCDATA)>
    <!ELEMENT titular (#PCDATA)>
    <!ATTLIST ticket
        codigo ID #REQUIRED
        emitido CDATA #REQUIRED
    >
    <!-- articulos -->
    <!ELEMENT articulos (articulo+)>
    <!ELEMENT articulo (nombreArticulo, cantidad, importeUnitarioSinIva,  importeIvaUnitario, importeUnitarioConIva, importe)>
    <!ELEMENT nombreArticulo (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT importeUnitarioSinIva (#PCDATA)>
    <!ELEMENT importeIvaUnitario (#PCDATA)>
    <!ELEMENT importeUnitarioConIva (#PCDATA)>
    <!ATTLIST articulo tipoIva (21|10|4) #REQUIRED>
]>
<facturacion>
    <comercio cif="A2345678A">
        <nombreComercio></nombreComercio>
        <direccionComercio></direccionComercio>
        <tlfComercio></tlfComercio>
    </comercio>
    <periodo>
        <inicioPeriodo>2022-02-10T10:00:00Z</inicioPeriodo>
        <finPeriodo>2022-02-10T23:00:00Z</finPeriodo>
    </periodo>
    <tickets>
        <ticket codigo="T0123456789" emitido="2022-01-10T10:53:12Z">
            <importeSinIva>300</importeSinIva>
            <importeIva>30</importeIva>
            <importe>330</importe>
            <formaPago>
                <!-- Si se usa efectivo el XML sería así. -->
                <!--<efectivo/> -->
                <tarjeta>
                    <numeracion>1234</numeracion>
                    <titular>José Luis López Alvarez</titular>
                </tarjeta>
            </formaPago>
            <articulos>
                <articulo tipoIva="10">
                    <nombreArticulo></nombreArticulo>
                    <cantidad>2</cantidad>
                    <importeUnitarioSinIva>100</importeUnitarioSinIva>
                    <importeIvaUnitario>10</importeIvaUnitario>
                    <importeUnitarioConIva>110</importeUnitarioConIva>
                    <importe>220</importe>
                </articulo>
            </articulos>
        </ticket>
    </tickets>
</facturacion>