<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE temporada [
    <!ELEMENT temporada (jornada+)>
    <!ELEMENT jornada (partido*)>
    <!-- No puede aparecer a la vez resultado y aplazado -->
    <!ELEMENT partido (fecha, estadio, local, visitante, (resultado | aplazado))>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT estadio (#PCDATA)>
    <!ELEMENT local (#PCDATA)>
    <!ELEMENT visitante (#PCDATA)>
    <!ELEMENT resultado EMPTY>
    <!--Atributos-->
    <!ATTLIST temporada anio CDATA #REQUIRED>
    <!ATTLIST jornada numero CDATA #REQUIRED>
    <!ATTLIST partido numero CDATA #REQUIRED>
    <!ATTLIST estadio espectadores CDATA #IMPLIED>
    <!ATTLIST resultado local CDATA #REQUIRED>
    <!ATTLIST resultado vistante CDATA #REQUIRED>
    <!ELEMENT aplazado EMPTY>
]>
<temporada anio="2000">
    <jornada numero="1">
        <partido numero="1">
            <fecha>200-02-02</fecha>
            <estadio espectadores="49000">La condomina</estadio>
            <local>RC Murcia</local>
            <visitante>Real Sociedad</visitante>
            <resultado local="3" vistante="2" />
        </partido>
        <partido numero="2">
            <fecha>200-02-03</fecha>
            <estadio>Santiago Bernabeu</estadio>
            <local>Real Madrid</local>
            <visitante>Villareal</visitante>
            <aplazado />
        </partido>
    </jornada>
    <jornada numero="2">
        <!-- AquÃ­ datos de la Jornada 2 -->
    </jornada>
</temporada>