=== Garchypielago/LLMM/LLMM_VCS/XML/DTD-XSD/XSD/Ej_10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="liga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="partidos"></xs:element>
                <xs:element name="equipos"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="partidos">
        <xs:sequence>
            <xs:element name="partido" type="partidoinfo" minOccurs="2" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="partidoinfo">
        <xs:sequence>
            <xs:element name="local" type="enjuego"></xs:element>
            <xs:element name="visitante" type="enjuego"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="enjuego">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"></xs:element>
            <xs:element name="goles" type="xs:nonNegativeInteger" default="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="equipos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="equipo" type="infoequipo" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="infoequipo">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"></xs:element>
            <xs:element name="entrenador" type="xs:string"></xs:element>
            <xs:element name="localidad" type="xs:string"></xs:element>
            <xs:element name="rank" type="xs:nonNegativeInteger" default="0"></xs:element>
            <xs:element name="partidosjugados" type="infojugados"></xs:element>
            <xs:element name="golmedia" type="infogoles"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="infojugados">
        <xs:sequence>
            <xs:element name="total" type="xs:nonNegativeInteger" default="0"></xs:element>
            <xs:element name="perdidos" type="xs:nonNegativeInteger" default="0"></xs:element>
            <xs:element name="empatados" type="xs:nonNegativeInteger" default="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="infogoles">
        <xs:sequence>
            <xs:element name="marcados" type="xs:nonNegativeInteger" default="0"></xs:element>
            <xs:element name="contra" type="xs:nonNegativeInteger" default="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Garchypielago/LLMM/LLMM_VCS/XML/XSD/Ej_10.xml
<?xml version="1.0" encoding="UTF-8"?>

<liga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Ej_10.xsd">
    <partidos>
        <partido>
            <local>
                <nombre> Alpedrete </nombre>
                <goles> 0 </goles>
            </local>
            <visitante>
                <nombre> Madracos </nombre>
                <goles> 1 </goles>
            </visitante>
        </partido>
        <partido>
            <local>
                <nombre> Guadarrama </nombre>
                <goles> 3 </goles>
            </local>
            <visitante>
                <nombre> Villaba </nombre>
                <goles> 3 </goles>
            </visitante>
        </partido>
        <partido>
            <local>
                <nombre> CD EL Escorial </nombre>
                <goles> 4 </goles>
            </local>
            <visitante>
                <nombre> Torrelodones </nombre>
                <goles> 2 </goles>
            </visitante>
        </partido>
    </partidos>

    <equipos>
        <equipo>
            <nombre></nombre>
            <entrenador></entrenador>
            <localidad></localidad>
            <rank></rank>
            <partidosjugados>
                <total></total>
                <perdidos></perdidos>
                <empatados></empatados>
            </partidosjugados>
            <golmedia>
                <marcados></marcados>
                <contra></contra>
            </golmedia>
        </equipo>
    </equipos>

</liga>
