<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE geografiaMundial [
    <!ELEMENT geografiaMundial (pais+)>
    <!ELEMENT pais (nombrePais, continente, capital)>
    <!ELEMENT nombrePais (#PCDATA)>
    <!ELEMENT continente (#PCDATA)>
    <!ELEMENT capital (#PCDATA)>
]>
<geografiaMundial>
    <pais>
        <nombrePais>Espa√±a</nombrePais>
        <continente>Europa</continente>
        <capital>Madrid</capital>
    </pais>
</geografiaMundial>