=== Garchypielago/LLMM/LLMM_VCS/XML/DTD/Ej_01-10/Ej_10.dtd
<!ELEMENT liga (partidos, equipos)>

<!ELEMENT partidos (partido*)>
<!ELEMENT partido (local, visitante)>
<!ELEMENT local (nombreloc, goles)>
<!ELEMENT visitante (nombrevis, goles)>
<!ELEMENT nombreloc (#PCDATA)>
<!ELEMENT nombrevis (#PCDATA)>
<!ELEMENT goles (#PCDATA)>

<!ELEMENT equipos (equipo*)>
<!ELEMENT equipo (nombre, entrenador, localidad, rank, partidosjugados?, golmedia?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT rank (#PCDATA)>
<!ELEMENT partidosjugados (total, perdidos, empatados)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT perdidos (#PCDATA)>
<!ELEMENT empatados (#PCDATA)>
<!ELEMENT golmedia (marcados, contra)>
<!ELEMENT marcados (#PCDATA)>
<!ELEMENT contra (#PCDATA)>

=== Garchypielago/LLMM/LLMM_VCS/XML/DTD-XSD/DTD/Ej_01-10/Ej_10.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE liga SYSTEM "Ej_10.dtd">
<liga>
    <partidos>
        <partido>
            <local>
                <nombreloc> Alpedrete </nombreloc>
                <goles> 0 </goles>
            </local>
            <visitante>
                <nombrevis> Madracos </nombrevis>
                <goles> 1 </goles>
            </visitante>
        </partido>
        <partido>
            <local>
                <nombreloc> Guadarrama </nombreloc>
                <goles> 3 </goles>
            </local>
            <visitante>
                <nombrevis> Villaba </nombrevis>
                <goles> 3 </goles>
            </visitante>
        </partido>
        <partido>
            <local>
                <nombreloc> CD EL Escorial </nombreloc>
                <goles> 4 </goles>
            </local>
            <visitante>
                <nombrevis> Torrelodones </nombrevis>
                <goles> 2 </goles>
            </visitante>
        </partido>
    </partidos>

    <equipos>
        <equipo>
            <nombre></nombre>
            <entrenador></entrenador>
            <localidad></localidad>
            <rank></rank>
            <partidosjugados>
                <total></total>
                <perdidos></perdidos>
                <empatados></empatados>
            </partidosjugados>
            <golmedia>
                <marcados></marcados>
                <contra></contra>
            </golmedia>
        </equipo>
    </equipos>

</liga>
