<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE jornada [
    <!ELEMENT jornada (equipos, partidosJornada)>
    <!ELEMENT equipos (equipo+)>
    <!ELEMENT equipo (nombre, entrenador, localidad, partidos, golaveraje)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT entrenador (#PCDATA)>
    <!ELEMENT localidad (#PCDATA)>
    <!ELEMENT partidos (jugados, perdidos, empatados)>
    <!ELEMENT jugados (#PCDATA)>
    <!ELEMENT perdidos (#PCDATA)>
    <!ELEMENT empatados (#PCDATA)>
    <!ELEMENT golaveraje (favor, contra)>
    <!ELEMENT favor (#PCDATA)>
    <!ELEMENT contra (#PCDATA)>
    <!ELEMENT partidosJornada (partido+)>
    <!ELEMENT partido (local, visitante)>
    <!ELEMENT local (#PCDATA)>
    <!ELEMENT visitante (#PCDATA)>
    <!ATTLIST equipo
        posicion CDATA #REQUIRED
        capacidadEstadio CDATA #IMPLIED>
    <!ATTLIST partido
        golesLocal CDATA #REQUIRED
        golesVisitante CDATA #REQUIRED >
]>
<jornada>
    <equipos>
        <equipo posicion="3" capacidadEstadio="20000">
            <nombre></nombre>
            <entrenador></entrenador>
            <localidad></localidad>
            <partidos>
                <jugados></jugados>
                <perdidos></perdidos>
                <empatados></empatados>
            </partidos>
            <golaveraje>
                <favor></favor>
                <contra></contra>
            </golaveraje>
        </equipo>
    </equipos>
    <partidosJornada>
        <partido golesLocal="3" golesVisitante="3">
            <local></local>
            <visitante></visitante>
        </partido>
    </partidosJornada>
</jornada>