<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE jornada [
    <!ELEMENT jornada (equipos, partidosJornada)>
    <!ELEMENT equipos (equipo+)>
    <!ELEMENT equipo (nombre, entrenador, localidad, posicion, partidos, golaveraje)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT entrenador (#PCDATA)>
    <!ELEMENT localidad (#PCDATA)>
    <!ELEMENT posicion (#PCDATA)>
    <!ELEMENT partidos (jugados, perdidos, empatados)>
    <!ELEMENT jugados (#PCDATA)>
    <!ELEMENT perdidos (#PCDATA)>
    <!ELEMENT empatados (#PCDATA)>
    <!ELEMENT golaveraje (favor, contra)>
    <!ELEMENT favor (#PCDATA)>
    <!ELEMENT contra (#PCDATA)>
    <!ELEMENT partidosJornada (partido+)>
    <!ELEMENT partido (local, visitante, golesLocal, golesVisitante)>
    <!ELEMENT local (#PCDATA)>
    <!ELEMENT visitante (#PCDATA)>
    <!ELEMENT golesLocal (#PCDATA)>
    <!ELEMENT golesVisitante (#PCDATA)>
]>
<jornada>
    <equipos>
        <equipo>
            <nombre></nombre>
            <entrenador></entrenador>
            <localidad></localidad>
            <posicion></posicion>
            <partidos>
                <jugados></jugados>
                <perdidos></perdidos>
                <empatados></empatados>
            </partidos>
            <golaveraje>
                <favor></favor>
                <contra></contra>
            </golaveraje>
        </equipo>
    </equipos>
    <partidosJornada>
        <partido>
            <local></local>
            <visitante></visitante>
            <golesLocal></golesLocal>
            <golesVisitante></golesVisitante>
        </partido>
    </partidosJornada>
</jornada>