=== Garchypielago/LLMM/LLMM_VCS/XML/DTD-XSD/XSD/Ej_21-25/Ej_22.dtd
<!ELEMENT tienda (datosTienda,datosPeriodo,datosTicket)>

<!ELEMENT datosTienda (nombre,direccion,telefono*)>
<!ATTLIST datosTienda CIF ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>


<!ELEMENT datosPeriodo EMPTY>
<!ATTLIST datosPeriodo inicio CDATA #REQUIRED>
<!ATTLIST datosPeriodo final CDATA #REQUIRED>


<!ELEMENT datosTicket (importeIVA,importeConIVA,formaPago,articulos)>
<!ATTLIST datosTicket codTicket ID #REQUIRED>
<!ATTLIST datosTicket fecha CDATA #REQUIRED>
<!ATTLIST datosTicket importeSinIVA CDATA #REQUIRED>
<!ELEMENT importeIVA (#PCDATA)>
<!ELEMENT importeConIVA (#PCDATA)>
<!ELEMENT formaPago (efectivo|tarjeta)>
<!ELEMENT efectivo (#PCDATA)>
<!ELEMENT tarjeta (num,titular)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT titular (#PCDATA)>
<!ELEMENT articulos (producto+)>
<!ELEMENT producto (nombre,cantidad,porcentajeIVA,importeIVA,precioUniIVA,importeTotal)>
<!ATTLIST producto precioUniSinIVA CDATA #REQUIRED>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT porcentajeIVA (#PCDATA)>
<!ELEMENT precioUniIVA (#PCDATA)>
<!ELEMENT importeTotal (#PCDATA)>

=== Garchypielago/LLMM/LLMM_VCS/XML/XSD/Ej_21-25/Ej_21.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- <!DOCTYPE tienda SYSTEM "Ej_22.dtd">
<tienda>
    <datosTienda CIF="A0">
        <nombre>    </nombre>
        <direccion> </direccion>
        <telefono>  </telefono>
        <telefono>  </telefono>
    </datosTienda>

    <datosPeriodo inicio="" final=""/>

    <datosTicket codTicket="A1" fecha="" importeSinIVA="">
        <importeIVA>    </importeIVA>
        <importeConIVA> </importeConIVA>
        <formaPago>
            <efectivo>      </efectivo>
            <tarjeta>
                <num>       </num>
                <titular>   </titular> 
            </tarjeta>
        </formaPago>
        <articulos>
            <producto precioUniSinIVA="">
                <nombre>        </nombre>
                <cantidad>      </cantidad>
                <porcentajeIVA> </porcentajeIVA>
                <importeIVA>    </importeIVA>
                <precioUniIVA>  </precioUniIVA>
                <importeTotal>  </importeTotal>
            </producto>
        </articulos>
    </datosTicket>
</tienda> -->

<tienda>
    <datosTienda CIF="A0">
        <nombre>    </nombre>
        <direccion> </direccion>
        <telefono>  </telefono>
        <telefono>  </telefono>
    </datosTienda>

    <datosPeriodo inicio="" final=""/>

    <datosTicket codTicket="A1" fecha="" importeSinIVA="">
        <importeIVA>    </importeIVA>
        <importeConIVA> </importeConIVA>
        <formaPago>
            <!-- <efectivo>      </efectivo> -->
            <tarjeta>
                <num>       </num>
                <titular>   </titular> 
            </tarjeta>
        </formaPago>
        <articulos>
            <producto precioUniSinIVA="">
                <nombre>        </nombre>
                <cantidad>      </cantidad>
                <porcentajeIVA> </porcentajeIVA>
                <importeIVA>    </importeIVA>
                <precioUniIVA>  </precioUniIVA>
                <importeTotal>  </importeTotal>
            </producto>
        </articulos>
    </datosTicket>
</tienda>
